function result=vertexesOfBox(pos_center_obs, obstacle_bbox, dim_pos)

        obstacle_half_bbox=obstacle_bbox/2.0;

        if dim_pos==2
            result=[pos_center_obs + obstacle_half_bbox.*[1;1] ...
                    pos_center_obs + obstacle_half_bbox.*[1;-1] ...
                    pos_center_obs + obstacle_half_bbox.*[-1;1] ...
                    pos_center_obs + obstacle_half_bbox.*[-1;-1]];
            return;
        end

        result=[pos_center_obs + obstacle_half_bbox.*[1;1;1] ...
                pos_center_obs + obstacle_half_bbox.*[1;1;-1] ...
                pos_center_obs + obstacle_half_bbox.*[1;-1;1] ...
                pos_center_obs + obstacle_half_bbox.*[1;-1;-1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;1;1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;1;-1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;-1;1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;-1;-1]];

end